// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/mwan/v1/mwan.proto

package mwanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MWANAgent_GetHealth_FullMethodName      = "/mwan.v1.MWANAgent/GetHealth"
	MWANAgent_Ping_FullMethodName           = "/mwan.v1.MWANAgent/Ping"
	MWANAgent_GetConfigState_FullMethodName = "/mwan.v1.MWANAgent/GetConfigState"
	MWANAgent_GetSystemInfo_FullMethodName  = "/mwan.v1.MWANAgent/GetSystemInfo"
	MWANAgent_WatchEvents_FullMethodName    = "/mwan.v1.MWANAgent/WatchEvents"
	MWANAgent_GetBGPStatus_FullMethodName   = "/mwan.v1.MWANAgent/GetBGPStatus"
	MWANAgent_AnnounceRoutes_FullMethodName = "/mwan.v1.MWANAgent/AnnounceRoutes"
	MWANAgent_WithdrawRoutes_FullMethodName = "/mwan.v1.MWANAgent/WithdrawRoutes"
)

// MWANAgentClient is the client API for MWANAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MWANAgent runs inside the MWAN VM on virtio-vsock (e.g. port 50051).
type MWANAgentClient interface {
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetConfigState(ctx context.Context, in *GetConfigStateRequest, opts ...grpc.CallOption) (*GetConfigStateResponse, error)
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
	GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error)
	AnnounceRoutes(ctx context.Context, in *AnnounceRoutesRequest, opts ...grpc.CallOption) (*AnnounceRoutesResponse, error)
	WithdrawRoutes(ctx context.Context, in *WithdrawRoutesRequest, opts ...grpc.CallOption) (*WithdrawRoutesResponse, error)
}

type mWANAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewMWANAgentClient(cc grpc.ClientConnInterface) MWANAgentClient {
	return &mWANAgentClient{cc}
}

func (c *mWANAgentClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, MWANAgent_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MWANAgent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) GetConfigState(ctx context.Context, in *GetConfigStateRequest, opts ...grpc.CallOption) (*GetConfigStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigStateResponse)
	err := c.cc.Invoke(ctx, MWANAgent_GetConfigState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, MWANAgent_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MWANAgent_ServiceDesc.Streams[0], MWANAgent_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MWANAgent_WatchEventsClient = grpc.ServerStreamingClient[AgentEvent]

func (c *mWANAgentClient) GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBGPStatusResponse)
	err := c.cc.Invoke(ctx, MWANAgent_GetBGPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) AnnounceRoutes(ctx context.Context, in *AnnounceRoutesRequest, opts ...grpc.CallOption) (*AnnounceRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceRoutesResponse)
	err := c.cc.Invoke(ctx, MWANAgent_AnnounceRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mWANAgentClient) WithdrawRoutes(ctx context.Context, in *WithdrawRoutesRequest, opts ...grpc.CallOption) (*WithdrawRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawRoutesResponse)
	err := c.cc.Invoke(ctx, MWANAgent_WithdrawRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MWANAgentServer is the server API for MWANAgent service.
// All implementations must embed UnimplementedMWANAgentServer
// for forward compatibility.
//
// MWANAgent runs inside the MWAN VM on virtio-vsock (e.g. port 50051).
type MWANAgentServer interface {
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetConfigState(context.Context, *GetConfigStateRequest) (*GetConfigStateResponse, error)
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[AgentEvent]) error
	GetBGPStatus(context.Context, *GetBGPStatusRequest) (*GetBGPStatusResponse, error)
	AnnounceRoutes(context.Context, *AnnounceRoutesRequest) (*AnnounceRoutesResponse, error)
	WithdrawRoutes(context.Context, *WithdrawRoutesRequest) (*WithdrawRoutesResponse, error)
	mustEmbedUnimplementedMWANAgentServer()
}

// UnimplementedMWANAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMWANAgentServer struct{}

func (UnimplementedMWANAgentServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedMWANAgentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMWANAgentServer) GetConfigState(context.Context, *GetConfigStateRequest) (*GetConfigStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigState not implemented")
}
func (UnimplementedMWANAgentServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedMWANAgentServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedMWANAgentServer) GetBGPStatus(context.Context, *GetBGPStatusRequest) (*GetBGPStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBGPStatus not implemented")
}
func (UnimplementedMWANAgentServer) AnnounceRoutes(context.Context, *AnnounceRoutesRequest) (*AnnounceRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceRoutes not implemented")
}
func (UnimplementedMWANAgentServer) WithdrawRoutes(context.Context, *WithdrawRoutesRequest) (*WithdrawRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawRoutes not implemented")
}
func (UnimplementedMWANAgentServer) mustEmbedUnimplementedMWANAgentServer() {}
func (UnimplementedMWANAgentServer) testEmbeddedByValue()                   {}

// UnsafeMWANAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MWANAgentServer will
// result in compilation errors.
type UnsafeMWANAgentServer interface {
	mustEmbedUnimplementedMWANAgentServer()
}

func RegisterMWANAgentServer(s grpc.ServiceRegistrar, srv MWANAgentServer) {
	// If the following call panics, it indicates UnimplementedMWANAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MWANAgent_ServiceDesc, srv)
}

func _MWANAgent_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_GetConfigState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).GetConfigState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_GetConfigState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).GetConfigState(ctx, req.(*GetConfigStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MWANAgentServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MWANAgent_WatchEventsServer = grpc.ServerStreamingServer[AgentEvent]

func _MWANAgent_GetBGPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).GetBGPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_GetBGPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).GetBGPStatus(ctx, req.(*GetBGPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_AnnounceRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).AnnounceRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_AnnounceRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).AnnounceRoutes(ctx, req.(*AnnounceRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MWANAgent_WithdrawRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MWANAgentServer).WithdrawRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MWANAgent_WithdrawRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MWANAgentServer).WithdrawRoutes(ctx, req.(*WithdrawRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MWANAgent_ServiceDesc is the grpc.ServiceDesc for MWANAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MWANAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mwan.v1.MWANAgent",
	HandlerType: (*MWANAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _MWANAgent_GetHealth_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MWANAgent_Ping_Handler,
		},
		{
			MethodName: "GetConfigState",
			Handler:    _MWANAgent_GetConfigState_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _MWANAgent_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetBGPStatus",
			Handler:    _MWANAgent_GetBGPStatus_Handler,
		},
		{
			MethodName: "AnnounceRoutes",
			Handler:    _MWANAgent_AnnounceRoutes_Handler,
		},
		{
			MethodName: "WithdrawRoutes",
			Handler:    _MWANAgent_WithdrawRoutes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _MWANAgent_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mwan/v1/mwan.proto",
}
