package networkd

import (
	"fmt"
	"io"
	"log/slog"
	"strconv"

	"github.com/coreos/go-systemd/v22/unit"
)

// Marker opens every file this package writes. Pruning removes a file only
// when it carries this line, so a file the deploy owns is never touched.
const Marker = "# Generated by mwan from /etc/mwan/network.json. Do not edit."

// FilePrefix is the numeric prefix every rendered file name opens with. It
// only orders the network manager's reads against the files the deploy
// still owns, so one value serves every provider: each rendered file matches
// a distinct interface, and no two of them compete for one device.
const FilePrefix = "20"

// The lines the renderer builds rather than looks up in the placements
// table. Each is named by the interface itself rather than by a typed leaf:
// the .network file matches the device by the name the .link file gave it,
// a VLAN's .netdev carries the interface's name and kind, and a family with
// a gateway contributes two routes whose keys travel together.
const (
	sectionMatch  = "Match"
	sectionNetDev = "NetDev"
	sectionRoute  = "Route"
	keyName       = "Name"
	keyKind       = "Kind"
	keyGateway    = "Gateway"
	keyMetric     = "Metric"
	keyTable      = "Table"
	kindVLAN      = "vlan"
)

// The values the network manager takes for a boolean and the folded DHCP
// key, which names the families a client runs for.
const (
	valueYes  = "yes"
	valueNo   = "no"
	valueIPv4 = "ipv4"
	valueIPv6 = "ipv6"
)

// Render serializes one link's unit files and returns each file name mapped
// to its content. The typed leaves land first, each where the placements
// table puts it, then the built lines, then the free-form sections. A
// free-form section whose heading the typed layer emitted exactly once is
// appended to that section, because the network manager reads a repeated
// heading as one section; one whose heading the typed layer repeated, or
// never emitted, is appended as its own section, because a heading the
// typed layer repeats is one the network manager reads as a list of objects.
func Render(spec Spec) (map[string]string, error) {
	if spec.VLAN != nil && spec.HardwareAddress != "" {
		// The address lands in the .link file and a VLAN has no device match
		// to put in one; a .link file with no [Match] applies to every
		// device.
		return nil, fmt.Errorf("%s: hardware-address is set on a VLAN, which has no .link file to carry it", spec.Name)
	}
	files := newFileSet()
	if spec.VLAN != nil {
		files.add(FileNetdev, sectionNetDev, keyName, spec.Name)
		files.add(FileNetdev, sectionNetDev, keyKind, kindVLAN)
	}
	files.add(FileNetwork, sectionMatch, keyName, spec.Name)
	for _, line := range spec.typedLines() {
		where := placements[line.leaf]
		files.add(where.File, where.Section, where.Key, line.value)
	}
	for _, family := range spec.families() {
		files.appendSections(FileNetwork, staticRoutes(family, spec.TableID)...)
	}
	for _, file := range spec.Files {
		if file.Kind != FileLink && file.Kind != FileNetwork && file.Kind != FileNetdev {
			return nil, fmt.Errorf("%s: networkd file kind %q is not link, network, or netdev", spec.Name, file.Kind)
		}
		for _, section := range file.Sections {
			files.merge(file.Kind, section)
		}
	}
	rendered := make(map[string]string, len(files.kinds))
	for _, kind := range files.kinds {
		content, err := io.ReadAll(unit.SerializeSections(files.sections[kind]))
		if err != nil {
			slog.Error("networkd: serializing a unit file failed", "interface", spec.Name, "kind", kind, "err", err)
			return nil, fmt.Errorf("%s: serialize %s file: %w", spec.Name, kind, err)
		}
		rendered[fileName(spec.Name, kind)] = Marker + "\n" + string(content)
	}
	return rendered, nil
}

// fileName is the name a rendered file is written under: the fixed prefix,
// the interface's name, and the kind as its extension.
func fileName(iface string, kind FileKind) string {
	return FilePrefix + "-" + iface + "." + string(kind)
}

// typedLine is one typed leaf and the value it renders to.
type typedLine struct {
	leaf  string
	value string
}

// typedLines is every typed leaf the spec sets, in the order the lines are
// emitted, with each value in the form the network manager reads. The order
// within a section follows the hand-authored files this rendering replaced,
// so a diff against one reads line for line. The two dhcp leaves fold into
// one line, named for the first family that sets one.
func (s Spec) typedLines() []typedLine {
	var lines []typedLine
	if s.Match.Driver != "" {
		lines = append(lines, typedLine{leaf: "match.driver", value: s.Match.Driver})
	}
	if s.Match.HardwareAddress != "" {
		lines = append(lines, typedLine{leaf: "match.hardware-address", value: s.Match.HardwareAddress})
	}
	if s.VLAN == nil {
		lines = append(lines, typedLine{leaf: "name", value: s.Name})
	}
	if s.HardwareAddress != "" {
		lines = append(lines, typedLine{leaf: "hardware-address", value: s.HardwareAddress})
	}
	if s.VLAN != nil {
		lines = append(lines, typedLine{leaf: "vlan.id", value: strconv.Itoa(s.VLAN.ID)})
	}
	for _, family := range s.families() {
		for _, address := range family.shared.Addresses {
			lines = append(lines, typedLine{
				leaf:  family.name + ".address",
				value: address.IP.String() + "/" + strconv.Itoa(address.PrefixLength),
			})
		}
	}
	if dhcp, set := s.dhcpLine(); set {
		lines = append(lines, dhcp)
	}
	if s.IPv6 != nil && s.IPv6.AcceptRA != nil {
		lines = append(lines, typedLine{leaf: "ipv6.accept-ra", value: yesNo(*s.IPv6.AcceptRA)})
	}
	for _, family := range s.families() {
		if family.shared.Forwarding != nil {
			lines = append(lines, typedLine{leaf: family.name + ".forwarding", value: yesNo(*family.shared.Forwarding)})
		}
	}
	if s.IPv4 != nil && s.IPv4.leasesMetric() {
		lines = append(lines, typedLine{leaf: "ipv4.route-metric", value: strconv.Itoa(*s.IPv4.RouteMetric)})
	}
	if s.IPv6 != nil && s.IPv6.Delegation != nil {
		lines = append(lines, delegationLines(*s.IPv6.Delegation)...)
	}
	if s.IPv6 != nil && s.IPv6.leasesMetric() {
		lines = append(lines, typedLine{leaf: "ipv6.route-metric", value: strconv.Itoa(*s.IPv6.RouteMetric)})
	}
	return lines
}

// dhcpLine folds the two dhcp leaves into the one DHCP key the network
// manager takes, which names the families a client runs for. A family the
// spec does not configure runs none. The line is absent when neither family
// sets the leaf.
func (s Spec) dhcpLine() (typedLine, bool) {
	var none typedLine
	leaf := ""
	v4 := false
	v6 := false
	if s.IPv4 != nil && s.IPv4.DHCP != nil {
		leaf = "ipv4.dhcp"
		v4 = *s.IPv4.DHCP
	}
	if s.IPv6 != nil && s.IPv6.DHCP != nil {
		if leaf == "" {
			leaf = "ipv6.dhcp"
		}
		v6 = *s.IPv6.DHCP
	}
	if leaf == "" {
		return none, false
	}
	value := valueNo
	switch {
	case v4 && v6:
		value = valueYes
	case v4:
		value = valueIPv4
	case v6:
		value = valueIPv6
	}
	return typedLine{leaf: leaf, value: value}, true
}

// delegationLines renders the delegation leaves the spec sets, in the order
// the placements table lists them.
func delegationLines(delegation Delegation) []typedLine {
	var lines []typedLine
	if delegation.DUIDType != "" {
		lines = append(lines, typedLine{leaf: "delegation.duid-type", value: delegation.DUIDType})
	}
	if delegation.DUID != "" {
		lines = append(lines, typedLine{leaf: "delegation.duid", value: delegation.DUID})
	}
	if delegation.Hint.IsValid() {
		lines = append(lines, typedLine{leaf: "delegation.hint", value: delegation.Hint.String()})
	}
	if delegation.WithoutRA != "" {
		lines = append(lines, typedLine{leaf: "delegation.without-ra", value: delegation.WithoutRA})
	}
	if delegation.UseDelegatedPrefix != nil {
		lines = append(lines, typedLine{leaf: "delegation.use-delegated-prefix", value: yesNo(*delegation.UseDelegatedPrefix)})
	}
	if delegation.RouterLifetimeSeconds != nil {
		lines = append(lines, typedLine{
			leaf:  "delegation.router-lifetime-seconds",
			value: strconv.Itoa(*delegation.RouterLifetimeSeconds),
		})
	}
	return lines
}

// namedFamily is one configured family with the name its leaves carry.
type namedFamily struct {
	name   string
	shared Family
}

// families lists the families the spec configures, IPv4 first.
func (s Spec) families() []namedFamily {
	var families []namedFamily
	if s.IPv4 != nil {
		families = append(families, namedFamily{name: "ipv4", shared: s.IPv4.Family})
	}
	if s.IPv6 != nil {
		families = append(families, namedFamily{name: "ipv6", shared: s.IPv6.Family})
	}
	return families
}

// staticRoutes builds the two routes a family with a gateway contributes:
// the default route in the main table, carrying the metric when the family
// sets one, and the default route in the provider's own table, which the
// policy rules steer into. A family with no gateway leases its routes and
// contributes none.
func staticRoutes(family namedFamily, tableID int) []*unit.UnitSection {
	if !family.shared.Gateway.IsValid() {
		return nil
	}
	gateway := family.shared.Gateway.String()
	main := &unit.UnitSection{
		Section: sectionRoute,
		Entries: []*unit.UnitEntry{{Name: keyGateway, Value: gateway}},
	}
	if family.shared.RouteMetric != nil {
		main.Entries = append(main.Entries, &unit.UnitEntry{Name: keyMetric, Value: strconv.Itoa(*family.shared.RouteMetric)})
	}
	provider := &unit.UnitSection{
		Section: sectionRoute,
		Entries: []*unit.UnitEntry{
			{Name: keyGateway, Value: gateway},
			{Name: keyTable, Value: strconv.Itoa(tableID)},
		},
	}
	return []*unit.UnitSection{main, provider}
}

// yesNo renders a boolean the way the network manager reads one.
func yesNo(value bool) string {
	if value {
		return valueYes
	}
	return valueNo
}

// fileSet is the sections of each unit file kind a spec produces, in the
// order the kinds were first written to.
type fileSet struct {
	kinds    []FileKind
	sections map[FileKind][]*unit.UnitSection
}

func newFileSet() *fileSet {
	return &fileSet{kinds: nil, sections: make(map[FileKind][]*unit.UnitSection, 3)}
}

// add writes one line under a heading, into the section already carrying
// that heading when there is one and into a new section otherwise. Typed
// lines are grouped this way because their leaves are not emitted in
// section order.
func (f *fileSet) add(kind FileKind, section string, key string, value string) {
	entry := &unit.UnitEntry{Name: key, Value: value}
	for _, existing := range f.sections[kind] {
		if existing.Section == section {
			existing.Entries = append(existing.Entries, entry)
			return
		}
	}
	f.appendSections(kind, &unit.UnitSection{Section: section, Entries: []*unit.UnitEntry{entry}})
}

// appendSections adds sections to the end of a file, never merging them.
func (f *fileSet) appendSections(kind FileKind, sections ...*unit.UnitSection) {
	if len(sections) == 0 {
		return
	}
	if _, seen := f.sections[kind]; !seen {
		f.kinds = append(f.kinds, kind)
	}
	f.sections[kind] = append(f.sections[kind], sections...)
}

// merge places one free-form section: after the typed lines of the one
// section carrying its heading, or as its own section when no section or
// more than one carries it.
func (f *fileSet) merge(kind FileKind, section Section) {
	entries := make([]*unit.UnitEntry, 0, len(section.Entries))
	for _, entry := range section.Entries {
		entries = append(entries, &unit.UnitEntry{Name: entry.Key, Value: entry.Value})
	}
	var carrier *unit.UnitSection
	carriers := 0
	for _, existing := range f.sections[kind] {
		if existing.Section == section.Name {
			carrier = existing
			carriers++
		}
	}
	if carriers == 1 {
		carrier.Entries = append(carrier.Entries, entries...)
		return
	}
	f.appendSections(kind, &unit.UnitSection{Section: section.Name, Entries: entries})
}
