// Package linkboot configures udev naming for MWAN-managed physical links.
package linkboot

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"goodkind.io/mwan/internal/installfile"
	"goodkind.io/mwan/internal/interfaceintent"
	"goodkind.io/mwan/internal/networkd"
)

const marker = "# Generated by mwan for owned link naming. Do not edit."

const fileMode fs.FileMode = 0o644

// WriteDir installs udev naming files for owned physical links.
func WriteDir(directory string, connections []interfaceintent.Connection) (changed []string, returnErr error) {
	defer func() {
		if returnErr != nil {
			slog.Error("linkboot: reconcile name files failed", "directory", directory, "err", returnErr)
		} else {
			slog.Info("linkboot: name files reconciled", "directory", directory, "changed", changed)
		}
	}()
	desired := desiredFiles(connections)
	if err := checkConflicts(directory, desired, connections, nil); err != nil {
		return nil, err
	}
	changed = make([]string, 0)
	entries, err := os.ReadDir(directory)
	if err != nil {
		if os.IsNotExist(err) {
			if len(desired) == 0 {
				return changed, nil
			}
			return nil, fmt.Errorf("link name directory %s does not exist", directory)
		}
		return nil, fmt.Errorf("read link name directory: %w", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".link" {
			continue
		}
		if _, wanted := desired[entry.Name()]; wanted {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read link name %s: %w", path, err)
		}
		if !strings.HasPrefix(string(content), marker+"\n") {
			continue
		}
		if err := os.Remove(path); err != nil {
			return nil, fmt.Errorf("remove old link name %s: %w", path, err)
		}
		changed = append(changed, entry.Name())
	}
	for name, content := range desired {
		written, err := installfile.Write(filepath.Join(directory, name), []byte(content), fileMode)
		if err != nil {
			return nil, fmt.Errorf("write owned link name %s: %w", name, err)
		}
		if written {
			changed = append(changed, name)
		}
	}
	sort.Strings(changed)
	return changed, nil
}

// ValidateDir checks conflicts before writes. Retiring files must be regular networkd-generated files.
func ValidateDir(directory string, connections []interfaceintent.Connection, retiring ...string) error {
	desired := desiredFiles(connections)
	if len(desired) != 0 {
		info, err := os.Stat(directory)
		if err != nil {
			slog.Error("linkboot: stat name directory failed", "directory", directory, "err", err)
			return fmt.Errorf("stat link name directory %s: %w", directory, err)
		}
		if !info.IsDir() {
			return fmt.Errorf("link name path %s is not a directory", directory)
		}
	}
	return checkConflicts(directory, desired, connections, retiring)
}

func desiredFiles(connections []interfaceintent.Connection) map[string]string {
	desired := make(map[string]string)
	for _, connection := range connections {
		if connection.Owner != interfaceintent.OwnerMWAN || connection.Link == nil ||
			connection.Link.Kind != interfaceintent.KindPhysical {
			continue
		}
		match := connection.Link.Match.HardwareAddress
		if match == "" {
			continue
		}
		name := fileName(strings.ToLower(match))
		desired[name] = fmt.Sprintf("%s\n[Match]\nPermanentMACAddress=%s\n[Link]\nNamePolicy=\nName=%s\n",
			marker, match, connection.Name)
	}
	return desired
}

func fileName(id string) string {
	digest := sha256.Sum256([]byte(id))
	return "10-mwan-" + hex.EncodeToString(digest[:]) + ".link"
}

func checkConflicts(directory string, desired map[string]string, connections []interfaceintent.Connection, retiring []string) error {
	entries, err := os.ReadDir(directory)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		slog.Error("linkboot: read name directory failed", "directory", directory, "err", err)
		return fmt.Errorf("read link name directory: %w", err)
	}
	for _, connection := range connections {
		if connection.Owner != interfaceintent.OwnerMWAN || connection.Link == nil ||
			connection.Link.Kind != interfaceintent.KindPhysical || connection.Link.Match.HardwareAddress == "" {
			continue
		}
		if err := checkConnectionConflict(directory, desired, entries, connection, retiring); err != nil {
			return err
		}
	}
	return nil
}

func checkConnectionConflict(directory string, desired map[string]string, entries []os.DirEntry, connection interfaceintent.Connection, retiring []string) error {
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".link" {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			slog.Error("linkboot: read existing name file failed", "path", path, "err", err)
			return fmt.Errorf("read link name %s: %w", path, err)
		}
		if _, wanted := desired[entry.Name()]; wanted {
			if !entry.Type().IsRegular() {
				return fmt.Errorf("interface %s: desired link name file %s is not a regular file", connection.Name, path)
			}
			if !strings.HasPrefix(string(content), marker+"\n") {
				return fmt.Errorf("interface %s: desired link name file %s is not managed by mwan", connection.Name, path)
			}
			continue
		}
		rendered := entry.Type().IsRegular() && strings.HasPrefix(string(content), networkd.Marker+"\n")
		if slices.Contains(retiring, entry.Name()) && rendered {
			continue
		}
		if !strings.HasPrefix(string(content), marker+"\n") && mayMatch(content, connection.Link.Match.HardwareAddress, rendered) {
			return fmt.Errorf("interface %s: existing link name file %s may match the same device", connection.Name, path)
		}
	}
	return nil
}

func mayMatch(content []byte, hardwareAddress string, rendered bool) bool {
	inMatch := false
	matchedMACKey := false
	for line := range strings.SplitSeq(string(content), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "[") {
			inMatch = line == "[Match]"
			continue
		}
		if !inMatch || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, found := strings.Cut(line, "=")
		key = strings.TrimSpace(key)
		if !found || (key != "PermanentMACAddress" && key != "MACAddress") {
			continue
		}
		matchedMACKey = true
		for candidate := range strings.FieldsSeq(value) {
			if strings.EqualFold(candidate, hardwareAddress) {
				return true
			}
			if _, err := net.ParseMAC(candidate); err != nil {
				return true
			}
		}
	}
	// udev applies the first matching file. A rendered file name sorts after the owned name file.
	return !matchedMACKey && !rendered
}
