package main

import (
	"bytes"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"goodkind.io/mwan/internal/config"
	"goodkind.io/mwan/internal/netif"
	"goodkind.io/mwan/internal/networkjson"
)

// networkMinPath is the network configuration these tests render from. It is
// the instance document the schema gate already validates, and it carries the
// gateway's provider set: att on table 100, webpass on 200, monkeybrains on
// 300, with the internal link on enmwanbr0.
const networkMinPath = "../../yang/instances/network-min.json"

// configsRendered reads one file as the configs Jinja template renders it for
// the testbed gateway. These are the bytes the deploy writes today, captured
// from mwan/config/sysctl-mwan.conf.j2, mwan/config/rt_tables.j2 and
// mwan/wanconfig/nghttpx-wanconfig.conf.j2 with that gateway's inventory
// values, so a rendering difference here is a difference on the host.
func configsRendered(t *testing.T, name string) []byte {
	t.Helper()
	content, err := os.ReadFile(filepath.Join("testdata", "configs-rendered", name))
	if err != nil {
		t.Fatalf("read the deployed rendering of %s: %v", name, err)
	}
	return content
}

// TestRenderedSysctlMatchesTheDeployedTemplate proves the binary renders the
// kernel tunable file the deploy writes today, setting for setting.
//
// Four comment lines differ, and only those four. The binary writes the file
// now, so the provenance line cannot credit Ansible, and the three lines that
// named this site's ISPs name the interface instead, because the same binary
// runs at a site with other ISPs. Every line that sets a value is identical,
// in the same order, which is what systemd-sysctl and the kernel read.
func TestRenderedSysctlMatchesTheDeployedTemplate(t *testing.T) {
	t.Parallel()
	deployed := string(configsRendered(t, "sysctl-mwan.conf"))
	commentChanges := map[string]string{
		"# Generated by Ansible - interface names are templated from group_vars":      "# Rendered by mwan install from config.toml and network.json",
		"# Disable SLAAC on Webpass interface (prevents unwanted autoconf addresses)": "# Disable SLAAC on enwebpass0 (prevents unwanted autoconf addresses)",
		"# Disable source validation on Webpass WAN (needed for policy routing)":      "# Disable source validation on enwebpass0 (needed for policy routing)",
		"# Disable source validation on AT&T WAN (needed for policy routing)":         "# Disable source validation on enatt0 (needed for policy routing)",
	}
	want := deployed
	for old, replacement := range commentChanges {
		if !strings.Contains(want, old+"\n") {
			t.Fatalf("the deployed rendering no longer carries the line %q", old)
		}
		want = strings.Replace(want, old+"\n", replacement+"\n", 1)
	}

	got, err := renderGatewayFile("sysctl-mwan.conf.tmpl", sysctlInputs{
		InternalIface:         "enmwanbr0",
		DisableSLAACIfaces:    []string{"enwebpass0"},
		DisableRPFilterIfaces: []string{"enwebpass0", "enatt0"},
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	if string(got) != want {
		t.Fatalf("rendered sysctl file differs from the deployed one:\n%s", lineDiff(want, string(got)))
	}
	// The comment lines are the only difference, so every setting must come
	// through unchanged even if the substitution above ever went wrong.
	deployedSettings := parseSysctlSettings([]byte(deployed))
	renderedSettings := parseSysctlSettings(got)
	if len(deployedSettings) != len(renderedSettings) {
		t.Fatalf("settings count = %d, want %d", len(renderedSettings), len(deployedSettings))
	}
	for i, setting := range deployedSettings {
		if renderedSettings[i] != setting {
			t.Errorf("setting %d = %+v, want %+v", i, renderedSettings[i], setting)
		}
	}
}

// TestRenderedRoutingTablesMatchTheDeployedTemplate proves the routing table
// file is byte for byte the one the deploy writes, with the provider tables
// read from the network configuration and the reserved tables from
// config.toml.
func TestRenderedRoutingTablesMatchTheDeployedTemplate(t *testing.T) {
	t.Parallel()
	want := configsRendered(t, "rt_tables")

	got, err := renderGatewayFile("rt_tables.tmpl", rtTablesInputs{
		Providers: []routingTable{
			{TableID: 100, Name: "att"},
			{TableID: 200, Name: "webpass"},
			{TableID: 300, Name: "monkeybrains"},
		},
		ReservedTables: []routingTable{
			{TableID: 400, Name: "cloudflared"},
			{TableID: 500, Name: "oob"},
		},
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	if !bytes.Equal(got, want) {
		t.Fatalf("rendered rt_tables differs from the deployed one:\n%s",
			lineDiff(string(want), string(got)))
	}
}

// TestRenderedProxyConfigMatchesTheDeployedTemplate proves the front-end
// proxy configuration is byte for byte the one the deploy writes, with the
// management address and the exposed port from config.toml and rousette's own
// backend port from the binary.
func TestRenderedProxyConfigMatchesTheDeployedTemplate(t *testing.T) {
	t.Parallel()
	want := configsRendered(t, "nghttpx-wanconfig.conf")

	got, err := renderGatewayFile("nghttpx-wanconfig.conf.tmpl", nghttpxInputs{
		MgmtAddr:     "2001:db8:b01::213",
		RestconfPort: 10080,
		RousettePort: rousetteBackendPort,
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	if !bytes.Equal(got, want) {
		t.Fatalf("rendered proxy config differs from the deployed one:\n%s",
			lineDiff(string(want), string(got)))
	}
}

// TestProviderTablesOrderByTableNumber proves the provider list the file
// carries comes out in one order whatever order the map is walked in. The
// network configuration holds providers in a map, so without this the file
// would differ between two runs on the same gateway and the agent's
// configuration hash would move on its own.
func TestProviderTablesOrderByTableNumber(t *testing.T) {
	t.Parallel()
	network, err := networkjson.Load(networkMinPath, "../../internal/yangpub/schema")
	if err != nil {
		t.Fatalf("load the network configuration: %v", err)
	}

	first := providerTables(network)
	for range 20 {
		if got := providerTables(network); !equalTables(got, first) {
			t.Fatalf("provider order = %+v, want %+v", got, first)
		}
	}
	want := []routingTable{
		{TableID: 100, Name: "att"},
		{TableID: 200, Name: "webpass"},
		{TableID: 300, Name: "monkeybrains"},
	}
	if !equalTables(first, want) {
		t.Fatalf("provider tables = %+v, want %+v", first, want)
	}
}

func equalTables(got []routingTable, want []routingTable) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

// TestParseSysctlSettingsReadsTheFileTheWayTheKernelIsConfigured proves the
// settings the apply step works from are the ones the file sets: every
// comment line is dropped, the trailing comment on a value is dropped, and a
// multi-value setting keeps its whole value.
func TestParseSysctlSettingsReadsTheFileTheWayTheKernelIsConfigured(t *testing.T) {
	t.Parallel()
	settings := parseSysctlSettings(configsRendered(t, "sysctl-mwan.conf"))

	byKey := make(map[string]string, len(settings))
	for _, setting := range settings {
		if _, seen := byKey[setting.Key]; seen {
			t.Errorf("%s is set twice", setting.Key)
		}
		byKey[setting.Key] = setting.Value
	}
	for key, want := range map[string]string{
		"net.ipv4.ip_forward":                "1",
		"net.ipv6.conf.enwebpass0.autoconf":  "0",
		"net.ipv4.conf.enwebpass0.rp_filter": "0",
		"net.ipv4.conf.enatt0.rp_filter":     "0",
		"net.ipv6.conf.enmwanbr0.accept_ra":  "2",
		"net.netfilter.nf_conntrack_max":     "262144",
		"net.ipv6.conf.all.use_tempaddr":     "0",
		"net.ipv4.tcp_rmem":                  "4096 87380 67108864",
		"net.ipv4.tcp_max_syn_backlog":       "8192",
	} {
		if got := byKey[key]; got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
	for _, setting := range settings {
		if strings.HasPrefix(setting.Key, "#") || strings.Contains(setting.Value, "#") {
			t.Errorf("a comment reached the settings: %+v", setting)
		}
	}
}

// seedSysctl creates the file that holds one key below root, with the value
// the kernel would report.
func seedSysctl(t *testing.T, root string, relative string, value string) string {
	t.Helper()
	path := filepath.Join(root, "proc", "sys", relative)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(value+"\n"), 0o600); err != nil {
		t.Fatalf("seed %s: %v", path, err)
	}
	return path
}

// TestApplySysctlWritesOnlyTheDriftedKeys drives the real runner against a
// directory tree standing in for /proc/sys. A key already at the file's value
// must not be written, because writing a tunable is not always the no-op its
// unchanged value suggests; a key whose live value differs must be written;
// and a multi-value key the kernel reports tab separated must read as already
// correct against the space separated value in the file.
func TestApplySysctlWritesOnlyTheDriftedKeys(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	converged := seedSysctl(t, root, "net/ipv4/ip_forward", "1")
	drifted := seedSysctl(t, root, "net/ipv4/conf/enwebpass0/rp_filter", "2")
	tabbed := seedSysctl(t, root, "net/ipv4/tcp_rmem", "4096\t87380\t67108864")
	convergedBefore, err := os.Stat(converged)
	if err != nil {
		t.Fatalf("stat %s: %v", converged, err)
	}

	runner := netif.NewProcSysctlRunnerUnder(slog.New(slog.DiscardHandler), false, root)
	applied, missing, err := applySysctl(t.Context(), runner, []sysctlSetting{
		{Key: "net.ipv4.ip_forward", Value: "1"},
		{Key: "net.ipv4.conf.enwebpass0.rp_filter", Value: "0"},
		{Key: "net.ipv4.tcp_rmem", Value: "4096 87380 67108864"},
	})
	if err != nil {
		t.Fatalf("applySysctl: %v", err)
	}

	if len(missing) != 0 {
		t.Errorf("missing = %v, want none", missing)
	}
	want := []string{"net.ipv4.conf.enwebpass0.rp_filter = 0"}
	if strings.Join(applied, " ") != strings.Join(want, " ") {
		t.Fatalf("applied = %v, want %v", applied, want)
	}
	if onDisk := readTrimmed(t, drifted); onDisk != "0" {
		t.Errorf("%s = %q, want 0", drifted, onDisk)
	}
	convergedAfter, err := os.Stat(converged)
	if err != nil {
		t.Fatalf("stat %s: %v", converged, err)
	}
	if !convergedAfter.ModTime().Equal(convergedBefore.ModTime()) {
		t.Errorf("%s was written although it already held the file's value", converged)
	}
	if onDisk := readTrimmed(t, tabbed); onDisk != "4096\t87380\t67108864" {
		t.Errorf("%s = %q, want the tab separated value untouched", tabbed, onDisk)
	}
}

// TestApplySysctlLeavesAKeyTheRunningKernelLacks covers the first deploy of a
// gateway: the install runs before the deploy writes this gateway's networkd
// files, so an interface the file names does not exist yet. That key is
// reported and skipped, and the rest of the file still applies.
func TestApplySysctlLeavesAKeyTheRunningKernelLacks(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	present := seedSysctl(t, root, "net/ipv4/conf/enwebpass0/rp_filter", "2")

	runner := netif.NewProcSysctlRunnerUnder(slog.New(slog.DiscardHandler), false, root)
	applied, missing, err := applySysctl(t.Context(), runner, []sysctlSetting{
		{Key: "net.ipv4.conf.enatt0.3242.rp_filter", Value: "0"},
		{Key: "net.ipv4.conf.enwebpass0.rp_filter", Value: "0"},
	})
	if err != nil {
		t.Fatalf("applySysctl: %v", err)
	}

	if strings.Join(missing, " ") != "net.ipv4.conf.enatt0.3242.rp_filter" {
		t.Fatalf("missing = %v, want the absent VLAN link's key", missing)
	}
	if strings.Join(applied, " ") != "net.ipv4.conf.enwebpass0.rp_filter = 0" {
		t.Fatalf("applied = %v, want the key that exists", applied)
	}
	if onDisk := readTrimmed(t, present); onDisk != "0" {
		t.Errorf("%s = %q, want 0", present, onDisk)
	}
}

func readTrimmed(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return strings.TrimRight(string(content), "\n")
}

// TestGatewayRendersSkipsAFileWhoseSiteValuesAreNotConfiguredYet covers the
// gateway whose config.toml was rendered before the inventory carried these
// values. Writing a file without them would drop the reserved tables from the
// routing table names and leave the proxy without a port, so the run renders
// nothing and says which value it is waiting for.
func TestGatewayRendersSkipsAFileWhoseSiteValuesAreNotConfiguredYet(t *testing.T) {
	t.Parallel()
	network, err := networkjson.Load(networkMinPath, "../../internal/yangpub/schema")
	if err != nil {
		t.Fatalf("load the network configuration: %v", err)
	}
	var cfg config.Config
	cfg.MwanMgmtAddr = "2001:db8:b01::213"

	files, skipped, err := gatewayRenders(&cfg, network)
	if err != nil {
		t.Fatalf("gatewayRenders: %v", err)
	}

	if len(files) != 0 {
		t.Fatalf("rendered %d files, want none", len(files))
	}
	for _, want := range []string{sysctlMwanPath, rtTablesPath, nghttpxConfPath} {
		found := false
		for _, reason := range skipped {
			if strings.Contains(reason, want) {
				found = true
			}
		}
		if !found {
			t.Errorf("no skip line names %s; lines: %v", want, skipped)
		}
	}
}

// TestInstallApplyRendersTheGatewayFiles runs the verb for the wan role
// against a root holding the two files the deploy writes, and checks each
// rendered file lands at the path the deploy writes it to, with the bytes the
// configs template produces and the mode the deploy gives it. A second run
// changes nothing.
func TestInstallApplyRendersTheGatewayFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	seedGatewayConfig(t, root)

	output := runInstallChild(t, root)

	wantFiles := map[string]string{
		sysctlMwanPath:  "sysctl-mwan.conf",
		rtTablesPath:    "rt_tables",
		nghttpxConfPath: "nghttpx-wanconfig.conf",
	}
	for hostPath, golden := range wantFiles {
		path := filepath.Join(root, hostPath)
		onDisk, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("read %s: %v", hostPath, err)
			continue
		}
		if !strings.Contains(output, "wrote "+path) {
			t.Errorf("run output:\n%s\nwant a line naming %s", output, path)
		}
		want := configsRendered(t, golden)
		if golden == "sysctl-mwan.conf" {
			// The four comment lines the binary owns are checked against the
			// deployed rendering in TestRenderedSysctlMatchesTheDeployed
			// Template; here the settings are what matters.
			if !sameSysctlSettings(parseSysctlSettings(onDisk), parseSysctlSettings(want)) {
				t.Errorf("%s sets different values from the deployed rendering", hostPath)
			}
			continue
		}
		if !bytes.Equal(onDisk, want) {
			t.Errorf("%s differs from the deployed rendering:\n%s",
				hostPath, lineDiff(string(want), string(onDisk)))
		}
	}
	for hostPath := range wantFiles {
		info, err := os.Stat(filepath.Join(root, hostPath))
		if err != nil {
			t.Errorf("stat %s: %v", hostPath, err)
			continue
		}
		if info.Mode().Perm() != systemdUnitMode {
			t.Errorf("%s mode = %v, want %v", hostPath, info.Mode().Perm(), systemdUnitMode)
		}
	}

	second := runInstallChild(t, root)
	if !strings.Contains(second, "no change") {
		t.Fatalf("second run output:\n%s\nwant no change", second)
	}
	for hostPath := range wantFiles {
		if strings.Contains(second, "wrote "+filepath.Join(root, hostPath)) {
			t.Errorf("the second run rewrote %s", hostPath)
		}
	}
}

func sameSysctlSettings(got []sysctlSetting, want []sysctlSetting) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

// seedGatewayConfig puts the two files the deploy writes before the install
// under root: the runtime configuration and the network configuration.
func seedGatewayConfig(t *testing.T, root string) {
	t.Helper()
	dir := filepath.Join(root, "etc", "mwan")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("create %s: %v", dir, err)
	}
	copyInto(t, filepath.Join("testdata", "gateway-config.toml"), filepath.Join(dir, "config.toml"))
	copyInto(t, networkMinPath, filepath.Join(dir, "network.json"))
}

func copyInto(t *testing.T, source string, target string) {
	t.Helper()
	content, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("read %s: %v", source, err)
	}
	if err := os.WriteFile(target, content, 0o600); err != nil {
		t.Fatalf("write %s: %v", target, err)
	}
}

// lineDiff reports the first line that differs, with its neighbours, so a
// failure names the line rather than printing two whole files.
func lineDiff(want string, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")
	for i := range max(len(wantLines), len(gotLines)) {
		wantLine := ""
		if i < len(wantLines) {
			wantLine = wantLines[i]
		}
		gotLine := ""
		if i < len(gotLines) {
			gotLine = gotLines[i]
		}
		if wantLine != gotLine {
			return "line " + strconv.Itoa(i+1) + ":\n  want: " + wantLine + "\n  got:  " + gotLine
		}
	}
	return "no line differs; the files differ only in length"
}
